crawl/urls.py
from django.conf.urls import url,include
from . import views
urlpatterns=[
	url(r'^$',views.home,name="home"),
	url(r'^login/$',views.user_login,name="user_login"),
	url(r'^crawl$',views.crawl_home,name="crawl_home"),
	url(r'^start$',views.start_crawling,name="start_crawling"),
	url(r'^logout$',views.user_logout,name="user_logout"),
]

dj_crawler/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('crawl.urls')),
]

crawl/models.py
from __future__ import unicode_literals

from django.db import models

class ContentIdentifier(models.Model):
	dom=models.CharField(max_length=30)
	css_selector=models.CharField(max_length=100,blank=True)

	def __str__(self):
		if self.css_selector:
			return str(self.dom)+' class='+str(self.css_selector)
		else:
			return str(self.dom)

class Input(models.Model):
	name=models.CharField(max_length=100)
	created_on=models.DateTimeField(auto_now=True)
	updated_on=models.DateTimeField(auto_now=True)
	url=models.CharField(max_length=300)
	processed=models.BooleanField(default=False)
	category_container_identifier=models.ForeignKey(ContentIdentifier,related_name='category_container_identifier')
	category_name_identifier=models.ForeignKey(ContentIdentifier,related_name='category_name_identifier')
	category_title_identifier=models.ForeignKey(ContentIdentifier,related_name='category_title_identifier')
	category_summary_identifier=models.ForeignKey(ContentIdentifier,related_name='category_summary_identifier')
	post_container_identifier=models.ForeignKey(ContentIdentifier,related_name='post_container_identifier')
	post_title_identifier=models.ForeignKey(ContentIdentifier,related_name='post_title_identifier')
	post_summary_identifier=models.ForeignKey(ContentIdentifier,related_name='post_summary_identifier')
	post_link_identifier=models.ForeignKey(ContentIdentifier,related_name='post_link_identifier')

	def __str__(self):
		return self.name

class Post(models.Model):
	title=models.CharField(max_length=200)
	summary=models.TextField()
	link=models.CharField(max_length=300)
	input=models.ForeignKey(Input,on_delete=models.CASCADE)

class Category(models.Model):
	name=models.CharField(max_length=100)
	title=models.CharField(max_length=200)
	summary=models.TextField()
	created_on=models.DateTimeField(auto_now=True)
	updated_on=models.DateTimeField(auto_now=True)
	posts=models.ManyToManyField(Post)

crawl/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from .models import *
from bs4 import BeautifulSoup
import requests
from urlparse import urlparse,urljoin

# Create your views here.
def home(request):
	if request.user.is_authenticated():
		return redirect('/crawl')
	return render(request,'crawl/user_login.html');

def user_logout(request):
	logout(request)
	return render(request,'crawl/user_login.html');

def user_login(request):
	data=dict()
	if request.user.is_authenticated():
		return redirect('/crawl')
	if request.method!='POST':
		data['error']=True
		data['msg']='Invalid request type'
		return render(request,'crawl/user_login.html',data)	
	username=request.POST['username']
	password=request.POST['password']
	user=authenticate(username=username,password=password)
	if user:
		login(request,user)
		return redirect('/crawl')
	else:
		data['error']=True
		data['msg']='Invalid username'
	return render(request,'crawl/user_login.html',data)

@login_required
def crawl_home(request):
	data=dict()
	try:
		data['inputs']=Input.objects.all()
	except Exception as ex:
		data['error']=True
		data['msg']=str(ex)
	return render(request,'crawl/crawl_home.html',data)

@login_required
def start_crawling(request):
	for input in Input.objects.all().filter(processed=False):
		insert_categories(get_posts(input),input)
		input.processed=True;
	return redirect('/crawl')

def get_posts(input):
	headings=['h1','h2','h3','h4','h5','h6']
	parsed_uri = urlparse(input.url)
	domain = '{uri.scheme}://{uri.netloc}/'.format(uri=parsed_uri)
	soup=BeautifulSoup(requests.get(input.url).text,"html.parser")
	categories=[]
	# print 'container:',input.container_identifier
	for cat in soup.find_all(input.category_container_identifier.dom,class_=input.category_container_identifier.css_selector):
		category=dict()
		category_title=cat.find(class_=input.category_title_identifier.css_selector)
		if category_title:
			category_title=category_title.get_text()
		category['title']=category_title

		posts=[]
		for story in cat.find_all(input.post_container_identifier.dom,class_=input.post_container_identifier.css_selector):
			tmp_post=dict()	

			story_title=story.find(input.post_title_identifier.dom,class_=input.post_title_identifier.css_selector)
			if story_title:
				story_title=story_title.get_text()
			else:
				story_title=''
			# print story_title
			tmp_post['title']=story_title;

			# print 'post_summary=',input.post_summary_identifier
			story_summary=story.find(str(input.post_summary_identifier.dom),class_=str(input.post_summary_identifier.css_selector))
			if story_summary:
				story_summary=story_summary.get_text()
			else:
				story_summary=''
			# print story_summary
			tmp_post['summary']=story_summary;

			story_link=story.find("a")
			if story_link:
				story_link=story_link["href"]
				if not story_link.startswith('http'):
					story_link=urljoin(domain,story_link)
			else:
				story_link=''
			tmp_post['link']=story_link;
			posts.append(tmp_post)
		category['posts']=posts
		categories.append(category)
	return categories

def insert_posts(posts,category,input):
	if not category:
		print 'no category skipped inserting posts: ',posts
		return
	if not input:
		print 'no input skipped inserting posts:\n',posts
		return
	for p in posts:
		if set(['title','summary','link']).issubset(p.keys()):
			post=Post()
			post.title=p['title']
			post.summary=p['summary']
			post.link=p['link']
			post.input=input
			post.save()
			category.posts.add(post)
		else:
			print 'invalid post skipping:',p

def insert_categories(categories,input):
	if not categories:
		print 'no category skipped inserting categories: ',categories
		return
	if not input:
		print 'no input skipped inserting posts:\n',posts
		return
	for category in categories:
		cat=None
		if 'title' in category.keys() and category['title'] and len(category['title'].strip()) > 0:
			try:
				cat=Category.objects.get(name=category['title'])
			except:
				cat=Category()
				cat.name=category['title']
				cat.title=category['title']
				cat.summary=category['title']
			cat.save()
			insert_posts(category['posts'],cat,input)
		else:
			print 'invalid category skipping:',category

crawl/templates/crawl/base.html
{%load static%}
<html>
	<head>
		<title>Django Crawler</title>

		<link rel="stylesheet" type="text/css" href="{%static 'crawl/components/bootstrap/dist/css/bootstrap.min.css'%}" />
		<link rel="stylesheet" type="text/css" href="{%static 'crawl/components/flat-ui/dist/css/flat-ui.css'%}" />
		<link rel="stylesheet" type="text/css" href="{%static 'crawl/components/font-awesome/css/font-awesome.min.css'%}" />
		<link rel="stylesheet" type="text/css" href="{%static 'crawl/css/main.css'%}" />
		{% block head %}
		{% endblock %}
	</head>
	<body>
		<div class="container-fluid jumbotron">
			<h3 class="heading">Welcome to Crazy Crawler</h3>
		</div>
			{% block body %}
			{% endblock %}
		
		<div class="footer">
			<p>Copyright 2016&copy; Crazy Crawler</p>
		</div>
		<script src="{%static 'crawl/components/jquery/dist/jquery.min.js'%}"></script>
		<script src="{%static 'crawl/components/bootstrap/dist/js/bootstrap.min.js'%}"></script>
		{% block script %}
		{% endblock %}
	</body>
</html>

crawl/templates/crawl/crawl_home.html
{% extends 'crawl/base.html' %}
{% load static %}

{% block body %}
	<div class="container">
		<div class="col-xs-10 col-xs-offset-1">
			<div class="heading">
				{%if request.user.is_authenticated%}
					<a href="logout" class="btn btn-danger">Logout</a>
				{%endif%}
				<a href="start" class="btn btn-success">Start Crawling</a>
			</div>
			<br/>
			<div class="alert alert-info">
				<p><i class="fa fa-info-circle"></i> Please use <a href="/admin">Admin</a> section to:</p>
				<ul>
					<li>Delete existing Posts, Categories and Inputs</li>
					<li>Add new Inputs</li>
					<li>Update any of the above items</li>
				</ul>
				<p>I have added two Input sources click on start crawling button to get the posts from these two sources</p>
			</div>
			<ul>
				{%for input in inputs%}
					<li>
						<h3>{{input.name}}</h3>
						<ul class="post">
						{%for post in input.post_set.all%}
							<li>
								<h5>{{post.title}}</h5>
								{%for category in post.category_set.all%}
									<span class="label label-success">{{category.title}}</span>
								{%endfor%}
								<br/>
								<p>{{post.summary}}</p>
								<a class="btn btn-info" href="{{post.link}}">Read More..</a>

							</li>
						{%endfor%}
						</ul>
					</li>
				{%endfor%}
			</ul>
		</div>
	</div>
{% endblock %}

crawl/templates/crawl/user_login.html
{% extends 'crawl/base.html' %}
{% load static %}

{%block body%}
<div class="container">
	<div class="col-sm-6 col-sm-offset-3">
		<h3>Login to continue</h3>
		{%if error%}
			<div class="alert alert-danger">{{msg}}</div>
		{%endif%}
		<form action="/login/" method="post">
			{%csrf_token%}
			<div class="form-group ">
				<label class="">Username</label>
				<input class="form-control" type="text" placeholder="Username" name="username"/>
			</div>
			<div class="form-group">
				<label class="">Password</label>
				<input class="form-control" type="Password" placeholder="Password" name="password"/>
			</div>
			<div class="form-group">
				<button type="submit" class="btn btn-success">Submit</button>
				<button type="reset" class="btn btn-danger">Reset</button>
			</div>
		</form>
	</div>
</div>
{%endblock%}